src/objects/Trainee__c.object
<CustomObject>
    <description>All trainees details to be stored</description>
    <fields>
        <fullName>Workshop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workshop</label>
        <referenceTo>Workshop__c</referenceTo>
        <relationshipLabel>Trainees</relationshipLabel>
        <relationshipName>Trainees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workshop__c.object
<CustomObject>
    <description>This will be used to store workshop related details.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Workshop</label>
    <nameField>
        <label>Workshop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workshops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SelfEnrollController.cls
public class SelfEnrollController {
    // Variables
    private Id workshopId {get; set;}
    public Workshop__c workshopInstance {get; set;}
    public Trainee__c traineeInstance {get; set;}
    public Boolean isRegistered {get; set;}

    public SelfEnrollController() {
        workshopId = Apexpages.currentPage().getParameters().get('workshopid');
        traineeInstance = new Trainee__c();
        System.debug('workshopId -->' + workshopId);
        if (workshopId != null) {
            workshopInstance = [SELECT Id, Name, Description__c FROM Workshop__c WHERE Id =: workshopId];
        }
    }

    public void regiterTrainee() {
        System.debug('traineeInstance -->' + traineeInstance);
        if (workshopId != null) {
            traineeInstance.Workshop__c = workshopId;
        }
        //insert traineeInstance;
        isRegistered = true;
    }
}