src/objects/Trainee__c.object
<CustomObject>
    <description>All trainees details to be stored</description>
    <fields>
        <fullName>Trainee_Email__c</fullName>
        <label>Trainee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Workshop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workshop</label>
        <referenceTo>Workshop__c</referenceTo>
        <relationshipLabel>Trainees</relationshipLabel>
        <relationshipName>Trainees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workshop__c.object
<CustomObject>
    <description>This will be used to store workshop related details.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Workshop</label>
    <nameField>
        <label>Workshop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workshops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConfirmAttendanceController.cls
/**
 * This class will be used to handle all Workshop and related Attendance information for related trainess
 *
 * @author : workalonesf@gmail.com
 */
public class ConfirmAttendanceController {

    /**
     * Method to get all workshop related records
     */
    @RemoteAction
    public static List<Workshop__c> getAllWorkshopDetails() {
        List<Workshop__c> workshopList = [SELECT Id, Name, Description__c FROM Workshop__c];
        return workshopList;
    }

    /**
     * Method to get all trainees list based on workshop id passed
     */
    @RemoteAction
    public static List<Trainee__c> getAllRelatedTrainees(Id workshopId) {
        List<Trainee__c> relatesTraineeList = [SELECT Id, Name, Trainee_Email__c FROM Trainee__c WHERE Workshop__c =: workshopId];
        return relatesTraineeList;
    }
}